# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/danielito/Escritorio/Vivado_proyect/project_7_MIcroBlazer/project_7_MIcroBlazer.srcs/sources_1/bd/MicroGPIO/ip/MicroGPIO_lmb_bram_1/MicroGPIO_lmb_bram_1.xci
# IP: The module: 'MicroGPIO_lmb_bram_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/danielito/Escritorio/Vivado_proyect/project_7_MIcroBlazer/project_7_MIcroBlazer.gen/sources_1/bd/MicroGPIO/ip/MicroGPIO_lmb_bram_1/MicroGPIO_lmb_bram_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MicroGPIO_lmb_bram_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/danielito/Escritorio/Vivado_proyect/project_7_MIcroBlazer/project_7_MIcroBlazer.srcs/sources_1/bd/MicroGPIO/ip/MicroGPIO_lmb_bram_1/MicroGPIO_lmb_bram_1.xci
# IP: The module: 'MicroGPIO_lmb_bram_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/danielito/Escritorio/Vivado_proyect/project_7_MIcroBlazer/project_7_MIcroBlazer.gen/sources_1/bd/MicroGPIO/ip/MicroGPIO_lmb_bram_1/MicroGPIO_lmb_bram_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MicroGPIO_lmb_bram_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
